FROM nginx:alpine
COPY index.html /usr/share/nginx/html/index.html   

EXPOSE 80

# http -> default port 80
# https -> default port 443
# musql -> default port 1443
# telnet -> in use for testing port 

#docker build -t my-app-one .
#docker run -d -p 80:80 my -app


#docker build -t my-app-one .
#docker run -d -p 80:80 my -app